name: First Workflow
on:
  push:
    branches: [ main ]
    paths:
    - version.txt
  pull_request:
    branches: [ main ]
    paths:
    - version.txt
  release:
    types:
      - published
jobs:
  short-sleep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sleep 10s